name:                cis194
version:             0.1.0.0
github:              "keathley/cis194"
license:             BSD3
author:              "Chris Keathley"
maintainer:          "c@keathley.io"
copyright:           "2018 Chris Keathley"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/keathley/cis194#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- containers
- QuickCheck
- mtl

library:
  source-dirs: src

tests:
  cis194-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cis194
